---
- name: Install ddclient
  apt:
    name: ddclient
    state: present

- name: Configure ddclient
  template:
    src: ddclient.conf.j2
    dest: /etc/ddclient.conf
  notify: restart ddclient

- name: Enable and start ddclient service
  systemd:
    name: ddclient
    enabled: yes
    state: started