---
- name: Install Unbound
  apt:
    name: unbound
    state: present

- name: Configure Unbound
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
  notify: restart unbound

- name: Enable and start Unbound service
  systemd:
    name: unbound
    enabled: yes
    state: started