---
- name: Install WireGuard
  apt:
    name: wireguard-tools
    state: present

- name: Load WireGuard peer keys
  include_vars:
    file: "{{ playbook_dir }}/.secrets/wireguard_keys"
    name: wireguard_secrets

- name: Configure WireGuard interface
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
  notify: restart wireguard

- name: Enable and start WireGuard service
  systemd:
    name: wg-quick@wg0
    enabled: yes
    state: started